import {
  createLocalFontProcessor,
} from '@unocss/preset-web-fonts/local'
import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetUno,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

// Mini-unit baseline (8px) and base font size (16px) for conversions
const MINI_UNIT = 8
const BASE_FONT_SIZE = 16

/**
 * Carbon's pre-calculated type scale values in pixels.
 * Corresponds to `packages/type/src/scale.js -> scale`
 */
const CARBON_SCALE_PX = [
  12,
  14,
  16,
  18,
  20,
  24,
  28,
  32,
  36,
  42,
  48,
  54,
  60,
  68,
  76,
  84,
  92,
  102,
  112,
  122,
  132,
  144,
  156,
]

/**
 * Carbon's font weights.
 * Corresponds to `packages/type/src/fontWeight.js -> fontWeights`
 */
const CARBON_FONT_WEIGHTS = {
  light: 300,
  regular: 400,
  semibold: 600,
}

/**
 * Carbon's font families with fallbacks.
 * Corresponds to `packages/type/src/fontFamily.js -> fontFamilies`
 */
const CARBON_FONT_FAMILIES = {
  mono: '\'IBM Plex Mono\', \'Menlo\', \'DejaVu Sans Mono\', \'Bitstream Vera Sans Mono\', Courier, monospace',
  sans: '\'IBM Plex Sans\', system-ui, -apple-system, BlinkMacSystemFont, \'.SFNSText-Regular\', sans-serif',
  sansCondensed: '\'IBM Plex Sans Condensed\', \'Helvetica Neue\', Arial, sans-serif',
  sansHebrew: '\'IBM Plex Sans Hebrew\', \'Helvetica Hebrew\', \'Arial Hebrew\', sans-serif',
  serif: '\'IBM Plex Serif\', \'Georgia\', Times, serif',
}

/**
 * Converts a px value to rem string based on BASE_FONT_SIZE.
 * @param {number} pxValue
 * @returns {string} Rem string
 */
function pxToRem(pxValue: number) {
  return `${pxValue / BASE_FONT_SIZE}rem`
}

// Defined breakpoints (already present in the original UnoCSS config)
const breakpointsPx = {
  sm: 320, // 320px
  md: 672, // 672px
  lg: 1056, // 1056px
  xlg: 1312, // 1312px
  max: 1584, // 1584px
}

// Convert breakpoints to rem
const breakpointsRem = Object.fromEntries(
  Object.entries(breakpointsPx).map(([key, value]) => [
    key,
    pxToRem(value),
  ]),
)

// Pre-calculate spacing values for clarity
const spacingValues = {
  // spacing
  '01': pxToRem(MINI_UNIT * 0.25), // 2px -> 0.125rem
  '02': pxToRem(MINI_UNIT * 0.5), // 4px -> 0.25rem
  '03': pxToRem(MINI_UNIT * 1), // 8px -> 0.5rem
  '04': pxToRem(MINI_UNIT * 1.5), // 12px -> 0.75rem
  '05': pxToRem(MINI_UNIT * 2), // 16px -> 1rem
  '06': pxToRem(MINI_UNIT * 3), // 24px -> 1.5rem
  '07': pxToRem(MINI_UNIT * 4), // 32px -> 2rem
  '08': pxToRem(MINI_UNIT * 5), // 40px -> 2.5rem
  '09': pxToRem(MINI_UNIT * 6), // 48px -> 3rem
  '10': pxToRem(MINI_UNIT * 8), // 64px -> 4rem
  '11': pxToRem(MINI_UNIT * 10), // 80px -> 5rem
  '12': pxToRem(MINI_UNIT * 12), // 96px -> 6rem
  '13': pxToRem(MINI_UNIT * 20), // 160px -> 10rem

  // Container values
  'container01': pxToRem(MINI_UNIT * 3), // 24px -> 1.5rem
  'container02': pxToRem(MINI_UNIT * 4), // 32px -> 2rem
  'container03': pxToRem(MINI_UNIT * 5), // 40px -> 2.5rem
  'container04': pxToRem(MINI_UNIT * 6), // 48px -> 3rem
  'container05': pxToRem(MINI_UNIT * 8), // 64px -> 4rem

  // Fixed sizes
  'sizeXSmall': pxToRem(24), // 24px -> 1.5rem
  'sizeSmall': pxToRem(32), // 32px -> 2rem
  'sizeMedium': pxToRem(40), // 40px -> 2.5rem
  'sizeLarge': pxToRem(48), // 48px -> 3rem
  'sizeXLarge': pxToRem(64), // 64px -> 4rem
  'size2XLarge': pxToRem(80), // 80px -> 5rem

  // Icon sizes
  'iconSize01': '1rem', // Directly 1rem (16px)
  'iconSize02': '1.25rem', // Directly 1.25rem (20px)
}

export default defineConfig({
  shortcuts: [
    // --- Typography Tokens (Fixed Styles from Carbon Design System) ---
    // These shortcuts are generated by mapping Carbon's `styles.js` definitions
    // to UnoCSS utility classes. Fluid (breakpoint) styles are ignored.
    {
      // Small styles
      caption01: `text-[${pxToRem(CARBON_SCALE_PX[0])}] font-regular leading-[1.33333] tracking-[${pxToRem(0.32)}]`,
      caption02: `text-[${pxToRem(CARBON_SCALE_PX[1])}] font-regular leading-[1.28572] tracking-[${pxToRem(0.32)}]`,
      label01: `text-[${pxToRem(CARBON_SCALE_PX[0])}] font-regular leading-[1.33333] tracking-[${pxToRem(0.32)}]`,
      label02: `text-[${pxToRem(CARBON_SCALE_PX[1])}] font-regular leading-[1.28572] tracking-[${pxToRem(0.16)}]`,
      helperText01: `text-[${pxToRem(CARBON_SCALE_PX[0])}] leading-[1.33333] tracking-[${pxToRem(0.32)}]`, // No specific font-weight
      helperText02: `text-[${pxToRem(CARBON_SCALE_PX[1])}] leading-[1.28572] tracking-[${pxToRem(0.16)}]`, // No specific font-weight

      // Body styles
      bodyCompact01: `text-[${pxToRem(CARBON_SCALE_PX[1])}] font-regular leading-[1.28572] tracking-[${pxToRem(0.16)}]`,
      body01: `text-[${pxToRem(CARBON_SCALE_PX[1])}] font-regular leading-[1.42857] tracking-[${pxToRem(0.16)}]`,
      bodyCompact02: `text-[${pxToRem(CARBON_SCALE_PX[2])}] font-regular leading-[1.375] tracking-[0]`,
      body02: `text-[${pxToRem(CARBON_SCALE_PX[2])}] font-regular leading-[1.5] tracking-[0]`,

      // Code styles
      code01: `font-mono text-[${pxToRem(CARBON_SCALE_PX[0])}] font-regular leading-[1.33333] tracking-[${pxToRem(0.32)}]`,
      code02: `font-mono text-[${pxToRem(CARBON_SCALE_PX[1])}] font-regular leading-[1.42857] tracking-[${pxToRem(0.32)}]`,

      // Fixed Heading styles
      heading01: `text-[${pxToRem(CARBON_SCALE_PX[1])}] font-semibold leading-[1.42857] tracking-[${pxToRem(0.16)}]`,
      headingCompact01: `text-[${pxToRem(CARBON_SCALE_PX[1])}] font-semibold leading-[1.28572] tracking-[${pxToRem(0.16)}]`,
      heading02: `text-[${pxToRem(CARBON_SCALE_PX[2])}] font-semibold leading-[1.5] tracking-[0]`,
      headingCompact02: `text-[${pxToRem(CARBON_SCALE_PX[2])}] font-semibold leading-[1.375] tracking-[0]`,
      heading03: `text-[${pxToRem(CARBON_SCALE_PX[4])}] font-regular leading-[1.4] tracking-[0]`,
      heading04: `text-[${pxToRem(CARBON_SCALE_PX[6])}] font-regular leading-[1.28572] tracking-[0]`,
      heading05: `text-[${pxToRem(CARBON_SCALE_PX[7])}] font-regular leading-[1.25] tracking-[0]`,
      heading06: `text-[${pxToRem(CARBON_SCALE_PX[9])}] font-light leading-[1.199] tracking-[0]`,
      heading07: `text-[${pxToRem(CARBON_SCALE_PX[11])}] font-light leading-[1.199] tracking-[0]`,

      // Expressive Heading styles (base styles only, ignoring fluid breakpoints as requested)
      expressiveHeading01: `text-[${pxToRem(CARBON_SCALE_PX[1])}] font-semibold leading-[1.25] tracking-[${pxToRem(0.16)}]`, // Based on heading01, changed lineHeight
      expressiveHeading02: `text-[${pxToRem(CARBON_SCALE_PX[2])}] font-semibold leading-[1.5] tracking-[0]`, // Based on heading02
      expressiveHeading03: `text-[${pxToRem(CARBON_SCALE_PX[4])}] font-regular leading-[1.4] tracking-[0]`,
      expressiveHeading04: `text-[${pxToRem(CARBON_SCALE_PX[6])}] font-regular leading-[1.28572] tracking-[0]`,
      expressiveHeading05: `text-[${pxToRem(CARBON_SCALE_PX[7])}] font-regular leading-[1.25] tracking-[0]`,
      expressiveHeading06: `text-[${pxToRem(CARBON_SCALE_PX[7])}] font-semibold leading-[1.25] tracking-[0]`, // Same fontSize as 05, but semibold weight
      expressiveParagraph01: `text-[${pxToRem(CARBON_SCALE_PX[5])}] font-light leading-[1.334] tracking-[0]`,

      // Quotation styles (base styles only, ignoring fluid breakpoints as requested)
      quotation01: `font-serif text-[${pxToRem(CARBON_SCALE_PX[4])}] font-regular leading-[1.3] tracking-[0]`,
      quotation02: `font-serif text-[${pxToRem(CARBON_SCALE_PX[7])}] font-light leading-[1.25] tracking-[0]`,

      // Display styles (base styles only, ignoring fluid breakpoints as requested)
      display01: `text-[${pxToRem(CARBON_SCALE_PX[9])}] font-light leading-[1.19] tracking-[0]`,
      display02: `text-[${pxToRem(CARBON_SCALE_PX[9])}] font-semibold leading-[1.19] tracking-[0]`,
      display03: `text-[${pxToRem(CARBON_SCALE_PX[9])}] font-light leading-[1.19] tracking-[0]`,
      display04: `text-[${pxToRem(CARBON_SCALE_PX[9])}] font-light leading-[1.19] tracking-[0]`,

      // V11 Aliases (mapping directly to the defined base shortcuts)
      legal01: 'caption01',
      legal02: 'bodyCompact01',
    },

    // --- Global Reset / Base Styles ---
    // Mimics parts of packages/type/src/reset.js
    // These could be applied to `body` element or globally via `@apply` in CSS.
    {
      'carbon-base-text': `font-sans font-regular text-rendering-optimizeLegibility antialiased moz-osx-font-smoothing-grayscale`,
      // For strong tags
      'carbon-strong-weight': `font-semibold`,
      // For code tags
      'carbon-code-font': `font-mono`,
    },
  ],
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons(),
    // 排版预设，用于处理 Markdown 渲染等
    presetTypography(),
    presetWebFonts({
      // We list the font families Carbon uses here so UnoCSS can fetch them (if web fonts)
      // or ensure local font processing via createLocalFontProcessor.
      fonts: {
        'mono': 'IBM Plex Mono',
        'sans': 'IBM Plex Sans',
        'sans-condensed': 'IBM Plex Sans Condensed',
        'sans-hebrew': 'IBM Plex Sans Hebrew',
        'serif': 'IBM Plex Serif',
        // Note: Carbon also lists other regional sans fonts, you might add them if needed:
        // 'sans-arabic': 'IBM Plex Sans Arabic',
        // 'sans-devanagari': 'IBM Plex Sans Devanagari',
        // 'sans-jp': 'IBM Plex Sans JP',
        // 'sans-kr': 'IBM Plex Sans KR',
        // 'sans-thai-looped': 'IBM Plex Sans Thai Looped',
        // 'sans-thai': 'IBM Plex Sans Thai',
      },
      processors: createLocalFontProcessor(),
    }),
  ],
  theme: {
    colors: {
      // 黑白颜色及其Hover状态
      'black': '#000000',
      'black-hover': '#212121', // 定义为单独的颜色，便于使用，例如 `bg-black-hover`
      'white': '#ffffff',
      'white-hover': '#e8e8e8', // 定义为单独的颜色

      // Carbon 设计系统中的主色系及其所有色阶
      'yellow': {
        10: '#fcf4d6',
        20: '#fddc69',
        30: '#f1c21b',
        40: '#d2a106',
        50: '#b28600',
        60: '#8e6a00',
        70: '#684e00',
        80: '#483700',
        90: '#302400',
        100: '#1c1500',
      },
      // Carbon 设计系统中的主色系Hover状态，这里定义为 'colorName-h' (h for hover)
      // 这样你可以明确地使用 `bg-yellow-h-50` 来获取 yellow50Hover
      'yellow-h': {
        10: '#f8e6a0',
        20: '#fccd27',
        30: '#ddb00e',
        40: '#bc9005',
        50: '#9e7700',
        60: '#755800',
        70: '#806000',
        80: '#5c4600',
        90: '#3d2e00',
        100: '#332600',
      },

      // 橙色
      'orange': {
        10: '#fff2e8',
        20: '#ffd9be',
        30: '#ffb784',
        40: '#ff832b',
        50: '#eb6200',
        60: '#ba4e00',
        70: '#8a3800',
        80: '#5e2900',
        90: '#3e1a00',
        100: '#231000',
      },
      'orange-h': {
        10: '#ffe2cc',
        20: '#ffc69e',
        30: '#ff9d57',
        40: '#fa6800',
        50: '#cc5500',
        60: '#9e4200',
        70: '#a84400',
        80: '#753300',
        90: '#522200',
        100: '#421e00',
      },

      // 红色
      'red': {
        10: '#fff1f1',
        20: '#ffd7d9',
        30: '#ffb3b8',
        40: '#ff8389',
        50: '#fa4d56',
        60: '#da1e28',
        70: '#a2191f',
        80: '#750e13',
        90: '#520408',
        100: '#2d0709',
      },
      'red-h': {
        10: '#ffe0e0',
        20: '#ffc2c5',
        30: '#ff99a0',
        40: '#ff6168',
        50: '#ee0713',
        60: '#b81922',
        70: '#c21e25',
        80: '#921118',
        90: '#66050a',
        100: '#540d11',
      },

      // 品红
      'magenta': {
        10: '#fff0f7',
        20: '#ffd6e8',
        30: '#ffafd2',
        40: '#ff7eb6',
        50: '#ee5396',
        60: '#d02670',
        70: '#9f1853',
        80: '#740937',
        90: '#510224',
        100: '#2a0a18',
      },
      'magenta-h': {
        10: '#ffe0ef',
        20: '#ffbdda',
        30: '#ff94c3',
        40: '#ff57a0',
        50: '#e3176f',
        60: '#b0215f',
        70: '#bf1d63',
        80: '#8e0b43',
        90: '#68032e',
        100: '#53142f',
      },

      // 紫色
      'purple': {
        10: '#f6f2ff',
        20: '#e8daff',
        30: '#d4bbff',
        40: '#be95ff',
        50: '#a56eff',
        60: '#8a3ffc',
        70: '#6929c4',
        80: '#491d8b',
        90: '#31135e',
        100: '#1c0f30',
      },
      'purple-h': {
        10: '#ede5ff',
        20: '#dcc7ff',
        30: '#c5a3ff',
        40: '#ae7aff',
        50: '#9352ff',
        60: '#7822fb',
        70: '#7c3dd6',
        80: '#5b24ad',
        90: '#40197b',
        100: '#341c59',
      },

      // 蓝色
      'blue': {
        10: '#edf5ff',
        20: '#d0e2ff',
        30: '#a6c8ff',
        40: '#78a9ff',
        50: '#4589ff',
        60: '#0f62fe',
        70: '#0043ce',
        80: '#002d9c',
        90: '#001d6c',
        100: '#001141',
      },
      'blue-h': {
        10: '#dbebff',
        20: '#b8d3ff',
        30: '#8ab6ff',
        40: '#5c97ff',
        50: '#1f70ff',
        60: '#0050e6',
        70: '#0053ff',
        80: '#0039c7',
        90: '#00258a',
        100: '#001f75',
      },

      // 青色
      'cyan': {
        10: '#e5f6ff',
        20: '#bae6ff',
        30: '#82cfff',
        40: '#33b1ff',
        50: '#1192e8',
        60: '#0072c3',
        70: '#00539a',
        80: '#003a6d',
        90: '#012749',
        100: '#061727',
      },
      'cyan-h': {
        10: '#cceeff',
        20: '#99daff',
        30: '#57beff',
        40: '#059fff',
        50: '#0f7ec8',
        60: '#005fa3',
        70: '#0066bd',
        80: '#00498a',
        90: '#013360',
        100: '#0b2947',
      },

      // 水鸭色
      'teal': {
        10: '#d9fbfb',
        20: '#9ef0f0',
        30: '#3ddbd9',
        40: '#08bdba',
        50: '#009d9a',
        60: '#007d79',
        70: '#005d5d',
        80: '#004144',
        90: '#022b30',
        100: '#081a1c',
      },
      'teal-h': {
        10: '#acf6f6',
        20: '#57e5e5',
        30: '#25cac8',
        40: '#07aba9',
        50: '#008a87',
        60: '#006b68',
        70: '#007070',
        80: '#005357',
        90: '#033940',
        100: '#0f3034',
      },

      // 绿色
      'green': {
        10: '#defbe6',
        20: '#a7f0ba',
        30: '#6fdc8c',
        40: '#42be65',
        50: '#24a148',
        60: '#198038',
        70: '#0e6027',
        80: '#044317',
        90: '#022d0d',
        100: '#071908',
      },
      'green-h': {
        10: '#b6f6c8',
        20: '#74e792',
        30: '#36ce5e',
        40: '#3bab5a',
        50: '#208e3f',
        60: '#166f31',
        70: '#11742f',
        80: '#05521c',
        90: '#033b11',
        100: '#0d300f',
      },

      // 灰度：酷灰
      'cool-gray': { // 使用 kebab-case，因为 UnoCSS 通常将驼峰转换为 kebab
        10: '#f2f4f8',
        20: '#dde1e6',
        30: '#c1c7cd',
        40: '#a2a9b0',
        50: '#878d96',
        60: '#697077',
        70: '#4d5358',
        80: '#343a3f',
        90: '#21272a',
        100: '#121619',
      },
      'cool-gray-h': {
        10: '#e4e9f1',
        20: '#cdd3da',
        30: '#adb5bd',
        40: '#9199a1',
        50: '#757b85',
        60: '#585e64',
        70: '#5d646a',
        80: '#434a51',
        90: '#2b3236',
        100: '#222a2f',
      },

      // 灰度：标准灰
      'gray': {
        10: '#f4f4f4',
        20: '#e0e0e0',
        30: '#c6c6c6',
        40: '#a8a8a8',
        50: '#8d8d8d',
        60: '#6f6f6f',
        70: '#525252',
        80: '#393939',
        90: '#262626',
        100: '#161616',
      },
      'gray-h': {
        10: '#e8e8e8',
        20: '#d1d1d1',
        30: '#b5b5b5',
        40: '#999999',
        50: '#7a7a7a',
        60: '#5e5e5e',
        70: '#636363',
        80: '#474747',
        90: '#333333',
        100: '#292929',
      },

      // 灰度：暖灰
      'warm-gray': {
        10: '#f7f3f2',
        20: '#e5e0df',
        30: '#cac5c4',
        40: '#ada8a8',
        50: '#8f8b8b',
        60: '#726e6e',
        70: '#565151',
        80: '#3c3838',
        90: '#272525',
        100: '#171414',
      },
      'warm-gray-h': {
        10: '#f0e8e6',
        20: '#d8d0cf',
        30: '#b9b3b1',
        40: '#9c9696',
        50: '#7f7b7b',
        60: '#605d5d',
        70: '#696363',
        80: '#4c4848',
        90: '#343232',
        100: '#2c2626',
      },
    },
    // --- Typography Theme Definition ---
    fontFamily: {
      // Mapping Carbon's font families
      'mono': CARBON_FONT_FAMILIES.mono,
      'sans': CARBON_FONT_FAMILIES.sans,
      'sans-condensed': CARBON_FONT_FAMILIES.sansCondensed,
      'sans-hebrew': CARBON_FONT_FAMILIES.sansHebrew,
      'serif': CARBON_FONT_FAMILIES.serif,
    },
    fontWeight: {
      // Explicitly define Carbon's named font weights. UnoCSS typically has these numbers too.
      light: String(CARBON_FONT_WEIGHTS.light),
      regular: String(CARBON_FONT_WEIGHTS.regular),
      semibold: String(CARBON_FONT_WEIGHTS.semibold),
    },

    lineHeight: {
      tight: 1.05,
      snug: 1.11,
      normal: 1.15,
      relaxed: 1.19,
      loose: 1.25,
    },

    letterSpacing: {
      tight: '-0.016rem', // -0.16px
      normal: '0',
      wide: '0.016rem', // 0.16px
    },
    breakpoints: breakpointsRem,
    spacing: {
      1: spacingValues['01'],
      2: spacingValues['02'],
      3: spacingValues['03'],
      4: spacingValues['04'],
      5: spacingValues['05'],
      6: spacingValues['06'],
      7: spacingValues['07'],
      8: spacingValues['08'],
      9: spacingValues['09'],
      10: spacingValues['10'],
      11: spacingValues['11'],
      12: spacingValues['12'],
      13: spacingValues['13'],
    },

    // 容器 Container - 映射到 max-width
    maxWidth: {
      'container-01': spacingValues.container01,
      'container-02': spacingValues.container02,
      'container-03': spacingValues.container03,
      'container-04': spacingValues.container04,
      'container-05': spacingValues.container05,
    },

    // 尺寸 Sizes (用于 width, height)
    // 根据原始代码，这些是通用的尺寸，命名也比较明确
    widths: {
      'x-small': spacingValues.sizeXSmall,
      'small': spacingValues.sizeSmall,
      'medium': spacingValues.sizeMedium,
      'large': spacingValues.sizeLarge,
      'x-large': spacingValues.sizeXLarge,
      '2x-large': spacingValues.size2XLarge,
    },
    heights: {
      'x-small': spacingValues.sizeXSmall,
      'small': spacingValues.sizeSmall,
      'medium': spacingValues.sizeMedium,
      'large': spacingValues.sizeLarge,
      'x-large': spacingValues.sizeXLarge,
      '2x-large': spacingValues.size2XLarge,
    }, // 通常高度和宽度尺寸相似，可以直接复用

    // 图标尺寸 Icon Sizes
    // 可以映射到 w-, h- 或 text-size
    iconSizes: {
      1: spacingValues.iconSize01,
      2: spacingValues.iconSize02,
    },
  },
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
  safelist: 'prose prose-sm m-auto text-left'.split(' '),
  // Add a global rule for html font-size, mimicking reset.js
  rules: [
    ['html', { 'font-size': '16px' }],
  ],
})
