/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Link: typeof import('./components/Link.vue')['default']
    NetworkParameterPanel: typeof import('./components/NetworkParameterPanel.vue')['default']
    OsnrChart: typeof import('./components/OsnrChart.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./components/Snackbar.vue')['default']
    SnackbarContainer: typeof import('./components/SnackbarContainer.vue')['default']
    TheDialog: typeof import('./components/TheDialog.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
  }
}
