/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllocationPanel: typeof import('./components/parameter-panels/allocation/AllocationPanel.vue')['default']
    AllocationParameterConfig: typeof import('./components/AllocationParameterConfig.vue')['default']
    AuthNav: typeof import('./components/AuthNav.vue')['default']
    CheckboxField: typeof import('./components/common/CheckboxField.vue')['default']
    copy: typeof import('./components/SimulationParameterConfig copy.vue')['default']
    DefragPanel: typeof import('./components/parameter-panels/defrag/DefragPanel.vue')['default']
    EdfaParametersPanel: typeof import('./components/parameter-panels/elements/EdfaParametersPanel.vue')['default']
    ElementPanelWrapper: typeof import('./components/parameter-panels/elements/ElementPanelWrapper.vue')['default']
    FiberParametersPanel: typeof import('./components/parameter-panels/elements/FiberParametersPanel.vue')['default']
    FusedParametersPanel: typeof import('./components/parameter-panels/elements/FusedParametersPanel.vue')['default']
    GlobalSimulationConfigPanel: typeof import('./components/parameter-panels/global/GlobalSimulationConfigPanel.vue')['default']
    GlobalSpanParametersPanel: typeof import('./components/parameter-panels/global/GlobalSpanParametersPanel.vue')['default']
    GlobalSpectrumInformationPanel: typeof import('./components/parameter-panels/global/GlobalSpectrumInformationPanel.vue')['default']
    InputField: typeof import('./components/common/InputField.vue')['default']
    Link: typeof import('./components/common/Link.vue')['default']
    NetworkParameterPanel: typeof import('./components/NetworkParameterPanel.vue')['default']
    OsnrChart: typeof import('./components/OsnrChart.vue')['default']
    PowerChart: typeof import('./components/PowerChart.vue')['default']
    RamanFiberParametersPanel: typeof import('./components/parameter-panels/elements/RamanFiberParametersPanel.vue')['default']
    RamanPumpConfigurator: typeof import('./components/parameter-panels/elements/RamanPumpConfigurator.vue')['default']
    README: typeof import('./components/README.md')['default']
    RoadmParametersPanel: typeof import('./components/parameter-panels/elements/RoadmParametersPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectField: typeof import('./components/common/SelectField.vue')['default']
    ServicePanel: typeof import('./components/parameter-panels/services/ServicePanel.vue')['default']
    ServiceParameterPanel: typeof import('./components/ServiceParameterPanel.vue')['default']
    SimulationPanel: typeof import('./components/parameter-panels/simulation/SimulationPanel.vue')['default']
    SimulationParameterConfig: typeof import('./components/SimulationParameterConfig.vue')['default']
    Snackbar: typeof import('./components/Snackbar.vue')['default']
    SnackbarContainer: typeof import('./components/SnackbarContainer.vue')['default']
    TheDialog: typeof import('./components/TheDialog.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TimeSlider: typeof import('./components/common/TimeSlider.vue')['default']
  }
}
