/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/docs/': RouteRecordInfo<'/docs/', '/docs', Record<never, never>, Record<never, never>>,
    '/network-editor/': RouteRecordInfo<'/network-editor/', '/network-editor', Record<never, never>, Record<never, never>>,
    '/network-editor/[id]': RouteRecordInfo<'/network-editor/[id]', '/network-editor/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/network-management/': RouteRecordInfo<'/network-management/', '/network-management', Record<never, never>, Record<never, never>>,
    '/README': RouteRecordInfo<'/README', '/README', Record<never, never>, Record<never, never>>,
    '/service-editor/': RouteRecordInfo<'/service-editor/', '/service-editor', Record<never, never>, Record<never, never>>,
    '/service-editor/[id]': RouteRecordInfo<'/service-editor/[id]', '/service-editor/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
